### PR TITLE
Fix for cocoalumberjack 2.0b

### PR DESCRIPTION
**Pull request by dmiedema**
Opening this up for discussion: 

This updates for CocoaLumberjack 2.0.0-beta4 release. Since its a pre-release I'll update this accordingly when i notice a new release has happened. 

Most of the changes are just with accessing variables and dealing with renames.

This should (probably) not be merged until v2.0.0 of CocoaLumberjack is officially released also.

### CODE REVIEW

**Comment by melke** [comment]
Hi @dmiedema I think I will wait for the official release of CocoaLumberJack. There are quite a few issues still in the betas, for example not being able to build using CocoaPods for certain deployment targets.

**Comment by ChrisChinchilla** [comment]
Hi there, I'm just wondering if this PR will fix some issues I've bene having with the latest version of XCode? If I follow the documentation it results in this error:

2015-02-11 06:02:41.399 LogglyTest[1558:84724] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: appname)'

There's a mention of variables up there in a commit message, so thought I'd check.

**Comment by melke** [comment]
Hi @ChrisChinchilla ,

I don't think this PR will help. For some reason it seems like the key CFBundleDisplayName is missing in the info.plist file in your xcode project. To resolve the problem, please insert this key in your plist file. Using xcode you can do this by selecting the plist file in the folder tree to the left, select the row "Information Property List" and click the plus sign to the right of this row. Then select "Bundle display name", press return. Double click the value column for this new row and enter a name for your app. This is the name that will show up beneath the app icon on the home screen, so choose a short name.
If you are using localized plist files, you need to do this in all of them. Hope this helps.

Cheers,
/Mats

**Comment by ChrisChinchilla** [comment]
Yeah, that works. Thanks. No idea why there wasn't one there.

**Comment by dmiedema** [comment]
Looks like [CocoaLumberjack 2.0](https://github.com/CocoaLumberjack/CocoaLumberjack/releases) was released today (about 20 minutes ago as of this comment) so this merge should be all good to go.

**Comment by melke** [comment]
Thanks @dmiedema I also added the new 2.0 imports and enums for flags and levels. Also using new major version 2.0.0, to note that the upgrade comes with breaking API changes, not in LogglyLoggerCocoaLumberjack, but in the dependency CocoaLumberjack 2.0.

**Pull request merged**
